version: '2'
catalog:
  questions:
  - variable: VERSION
    required: true
    default: latest
    type: string
  - variable: NAME
    required: true
    type: string
  - variable: TF_DOMAIN
    label: Traefik Domain
    required: true
    type: string
  - variable: TF_ALIAS
    label: Traefik Alias
    required: true
  - variable: DOMAIN
    label: Domain
    description: |
      The domain on which OroCommerce EE will be reachable
    required: true
    type: string
  - variable: BASE_REGISTRY
    description: |
      The docker registry to be used to pull base images from
    required: true
    type: string
    default: registry.gitlab.com/diepartments/orocommerce/images
  - variable: CONCRETE_REGISTRY
    description: |
      The docker registry to be used to pull concrete images from
    required: true
    type: string
  - variable: DB_NAME
    label: Database Name
    type: string
    required: true
    default: haneu_oro
  - variable: DB_USER
    label: Database User
    type: string
    required: true
    default: haneu
  - variable: DB_PASSWORD
    label: Database Password
    type: password
    required: true
    default: haneu
services:
  app:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 9000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  oro-cron:
    scale: 1
    start_on_create: true
  web:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 20000
      port: 80
      unhealthy_threshold: 5
      initializing_timeout: 300000
      interval: 30000
      strategy: recreate
      request_line: 'GET "/_healthz" "HTTP/1.1\r\nHost: ${DOMAIN}"'
      reinitializing_timeout: 300000
  oro-mq:
    scale: 1
    start_on_create: true
  postgres:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5432
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  orocommerceelastic:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 9200
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
